[package]
name = "wikiscan"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bzip2 = "0.4"
quick-xml = "0.31"
regex = "1"
memmap2 = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[[bin]]
name = "wikiscan"
path = "wikiscan.rs"
